Repository fusionjs/fusion-plugin-react-helmet-async, pull requests merged in 2018-10, with the labels that each got.

#72 Update dependencies and fix failing snapshot tests
  package.json
  src/__fixtures__/ssr1.html
  yarn.lock
Labels: dependencies, greenkeeping

#74 Upgrade dependency versions
  yarn.lock
Labels: greenkeeping

#79 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
